scrolling:
  history: 100000

font:
  normal:
    family: MesloLGS Nerd Font
    style: Regular
  size: 14.0

selection:
  save_to_clipboard: true

key_bindings:
  - { key: F12,                         action: ToggleFullscreen }
  - { key: F,      mods: Alt,           chars: "\x1bf" }
  - { key: B,      mods: Alt,           chars: "\x1bb" }
  - { key: Left,   mods: Alt,           chars: "\x1bb" }
  - { key: Right,  mods: Alt,           chars: "\x1bf" }
  # https://github.com/jwilm/alacritty/issues/93#issuecomment-427592040
  - { key: D,      mods: Alt,           chars: "\x1bd" }
  - { key: P,      mods: Alt,           chars: "\x1bp" }
  - { key: Equals, mods: Control|Shift, action: IncreaseFontSize }
  - { key: Plus,   mods: Control|Shift, action: IncreaseFontSize }
  - { key: Minus,  mods: Control|Shift, action: DecreaseFontSize }
  - { key: Minus,  mods: Control|Shift, action: DecreaseFontSize }
  - { key: Key0,   mods: Control|Shift, action: ResetFontSize    }

draw_bold_text_with_bright_colors: false
